ROBUSTNESS: Assert that Patient ID does not contain underscores [#81]

diff --git a/bin/lg3-cleanup b/bin/lg3-cleanup
--- a/bin/lg3-cleanup
+++ b/bin/lg3-cleanup
@@ -102,6 +102,8 @@ echo "Project = ${PROJECT}"
 echo "Patient = ${PATIENT:?}"
 echo "Samples = ${SAMPLES:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
 TRIMDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/trim
 ALIGNDATA=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes
diff --git a/bin/lg3-envir b/bin/lg3-envir
--- a/bin/lg3-envir
+++ b/bin/lg3-envir
@@ -9,3 +9,6 @@ echo "PROJECT=$PROJECT"
 echo "CONV=$CONV"
 echo "PATIENT=$PATIENT"
 echo "SAMPLES=$SAMPLES"
+
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
diff --git a/runs_demo/_run_Align_gz b/runs_demo/_run_Align_gz
--- a/runs_demo/_run_Align_gz
+++ b/runs_demo/_run_Align_gz
@@ -30,6 +30,8 @@ echo "- PATIENT=${PATIENT:?}"
 echo "- SAMPLES=${SAMPLES:?}"
 echo "- LG3_CHASTITY_FILTERING=${LG3_CHASTITY_FILTERING}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
 QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"
 
diff --git a/runs_demo/_run_Merge b/runs_demo/_run_Merge
--- a/runs_demo/_run_Merge
+++ b/runs_demo/_run_Merge
@@ -27,6 +27,8 @@ echo "- SAMPLE=${SAMPLE:?}"
 echo "- SAMPLES=${SAMPLES:?}"
 echo "- PATIENT=${PATIENT:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
 QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"
 
diff --git a/runs_demo/_run_Merge_QC b/runs_demo/_run_Merge_QC
--- a/runs_demo/_run_Merge_QC
+++ b/runs_demo/_run_Merge_QC
@@ -29,6 +29,8 @@ echo "- SAMPLES=${SAMPLES:?}"
 echo "- PATIENT=${PATIENT:?}"
 echo "- ILIST=${ILIST:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
 QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"
 
diff --git a/runs_demo/_run_MutDet b/runs_demo/_run_MutDet
--- a/runs_demo/_run_MutDet
+++ b/runs_demo/_run_MutDet
@@ -27,6 +27,8 @@ echo "- PATIENT=${PATIENT:?}"
 echo "- PROJECT=${PROJECT:?}"
 echo "- CONV=${CONV:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 [[ -f "$CONV" ]] || { echo "File not found: ${CONV}"; exit 1; }
 CONV=$(readlink -e "$CONV")
 
diff --git a/runs_demo/_run_Pindel b/runs_demo/_run_Pindel
--- a/runs_demo/_run_Pindel
+++ b/runs_demo/_run_Pindel
@@ -28,6 +28,8 @@ echo "- PATIENT=${PATIENT:?}"
 echo "- PROJECT=${PROJECT:?}"
 echo "- CONV=${CONV:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_INPUT_ROOT=${LG3_INPUT_ROOT},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
 QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"
 
diff --git a/runs_demo/_run_Recal b/runs_demo/_run_Recal
--- a/runs_demo/_run_Recal
+++ b/runs_demo/_run_Recal
@@ -33,6 +33,8 @@ echo "- NORMAL=${NORMAL:?}"
 echo "- ILIST=${ILIST:?}"
 echo "- EMAIL=${EMAIL}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 ## Assert that the patient file exists
 [[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
 ILIST=$(readlink -e "$ILIST")
diff --git a/runs_demo/_run_Recal_pass2 b/runs_demo/_run_Recal_pass2
--- a/runs_demo/_run_Recal_pass2
+++ b/runs_demo/_run_Recal_pass2
@@ -31,6 +31,8 @@ echo "- NORMAL=${NORMAL:?}"
 echo "- PATIENT=${PATIENT:?}"
 echo "- ILIST=${ILIST:?}"
 
+[[ "${PATIENT}" == *[_]* ]] && { echo "ERROR: 'PATIENT' must not contain underscores: ${PATIENT}"; exit 1; }
+
 [[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
 ILIST=$(readlink -e "$ILIST")
 
