lg3 status: Use double dash ('--') for long options

diff --git a/bin/lg3-status b/bin/lg3-status
--- a/bin/lg3-status
+++ b/bin/lg3-status
@@ -5,16 +5,16 @@
 ###  lg3 status [options] <patient> <patient2> ...
 ###
 ### Options:
-###  -conv=<pathame>         The path to the tab-delimited patient file
-###  -fastq=(true|false)     Check raw FASTQ files
-###  -trim=(true|false)      Check trimmed FASTQ files
-###  -bam=(true|false)       Check raw BAM files
-###  -bwa=(true|false)       Check aligned BAM files
-###  -recal=(true|false)     Check recalibrated output
-###  -germline=(true|false)  Check germline output
-###  -pindel=(true|false)    Check Pindel output
-###  -mutect=(true|false)    Check MutDet output
-###  -combined=(true|false)  Check mutation output
+###  --conv=<pathame>         The path to the tab-delimited patient file
+###  --fastq=(true|false)     Check raw FASTQ files
+###  --trim=(true|false)      Check trimmed FASTQ files
+###  --bam=(true|false)       Check raw BAM files
+###  --bwa=(true|false)       Check aligned BAM files
+###  --recal=(true|false)     Check recalibrated output
+###  --germline=(true|false)  Check germline output
+###  --pindel=(true|false)    Check Pindel output
+###  --mutect=(true|false)    Check MutDet output
+###  --combined=(true|false)  Check mutation output
 ###
 ### Examples:
 ###  lg3 status Patient157t
@@ -54,17 +54,17 @@ wcl() {
 #### Parse optional args
 while [ -n "$1" ]; do
 case $1 in
-    -conv*=*) CONV=${1#*=};shift 1;;
-    -bam*=*) BAM_SUFF=${1#*=};shift 1;;
-    -tr*=*) TRIM=${1#*=};shift 1;;
-    -f*=*) FQ=${1#*=};shift 1;;
-    -bwa*=*) BWA=${1#*=};shift 1;;
-    -rec*=*) REC=${1#*=};shift 1;;
-    -g*=*) GL=${1#*=};shift 1;;
-    -p*=*) PINDEL=${1#*=};shift 1;;
-    -m*=*) MUT=${1#*=};shift 1;;
-    -comb*=*) COMB=${1#*=};shift 1;;
-    -*) echo "error: no such option $1";exit 1;;
+    --conv*=*) CONV=${1#*=};shift 1;;
+    --bam*=*) BAM_SUFF=${1#*=};shift 1;;
+    --tr*=*) TRIM=${1#*=};shift 1;;
+    --f*=*) FQ=${1#*=};shift 1;;
+    --bwa*=*) BWA=${1#*=};shift 1;;
+    --rec*=*) REC=${1#*=};shift 1;;
+    --g*=*) GL=${1#*=};shift 1;;
+    --p*=*) PINDEL=${1#*=};shift 1;;
+    --m*=*) MUT=${1#*=};shift 1;;
+    --comb*=*) COMB=${1#*=};shift 1;;
+    --*) echo "error: no such option $1";exit 1;;
     *)  break;;
 esac
 done
