Major code refactoring with config files

diff --git a/prep_gnomAD_by_chr b/prep_gnomAD_by_chr
--- a/prep_gnomAD_by_chr
+++ b/prep_gnomAD_by_chr
@@ -1,31 +1,27 @@
 #!/bin/bash
 #### See https://github.com/broadinstitute/gatk/blob/master/scripts/mutect2_wdl/mutect_resources.wdl
+# shellcheck source=scripts/utils.sh
+source "${LG3_HOME:?}/scripts/utils.sh"
+source_lg3_conf
+
 PROGRAM=${BASH_SOURCE[0]}
 echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] BEGIN: $PROGRAM"
 echo "Call: ${BASH_SOURCE[*]}"
 echo "Script: $PROGRAM"
 echo "Arguments: $*"
 
-module load jdk/1.8.0
-module load htslib/1.7
+module load jdk/1.8.0 htslib/1.7
 
-LG3_HOME=/home/jocostello/shared/LG3_Pipeline
-LG3_HOME=${LG3_HOME:?}
-
-# shellcheck source=scripts/utils.sh
-source "${LG3_HOME}/scripts/utils.sh"
-
-GATK4="${LG3_HOME}/tools/gatk-4.0.12.0/gatk"
-assert_file_executable ${GATK4}
+assert_file_executable "${GATK4:?}"
 command_mem=100
 
 echo "Input: "
-echo "- LG3_HOME=${LG3_HOME:?}"
+echo "- LG3_HOME=${LG3_HOME}"
+echo "- GATK4=${GATK4}"
 
-#ILIST=${LG3_HOME}/resources/All_exome_targets.extended_200bp.bed
-ILIST=${LG3_HOME}/resources/All_but_chrM_targets.extended_200bp.bed
-echo "- ILIST=${ILIST:?}"
-assert_file_exists "${ILIST}"
+TARGET=${LG3_HOME}/resources/All_but_chrM_targets.extended_200bp.bed
+echo "- TARGET=${TARGET:?}"
+assert_file_exists "${TARGET}"
 
 MAF=0.001
 echo "- MAF=$MAF"
@@ -44,7 +40,7 @@ do
 	echo -e "\\nStep 1: SelectVariants ... "
 	OUT1=chr${CHR}_selected.vcf
 
-	{ time ${GATK4} --java-options "-Xmx${command_mem}g" SelectVariants -V ${GNOMAD} -L ${ILIST} -O ${OUT1} --lenient; } 2>&1 || { echo "FAILED"; exit 1; }
+	{ time ${GATK4} --java-options "-Xmx${command_mem}g" SelectVariants -V ${GNOMAD} -L "${TARGET}" -O ${OUT1} --lenient; } 2>&1 || { echo "FAILED"; exit 1; }
 	
 	echo -n "Output: "
 	wc -l ${OUT1}
diff --git a/runs_demo/_run_Mutect2 b/runs_demo/_run_Mutect2
--- a/runs_demo/_run_Mutect2
+++ b/runs_demo/_run_Mutect2
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # shellcheck source=scripts/utils.sh
-source "${LG3_HOME}/scripts/utils.sh"
+source "${LG3_HOME:?}/scripts/utils.sh"
+source_lg3_conf
 
 assert_pwd
 
@@ -11,16 +12,12 @@ echo "Call: ${BASH_SOURCE[*]}"
 echo "Script: $PROGRAM"
 echo "Arguments: $*"
 
-LG3_HOME=${LG3_HOME:?}
 LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
 LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
 EMAIL=${EMAIL:?}
 PATIENT=${PATIENT:-Patient157t10}
-PROJECT=${PROJECT:-LG3}
-CONV=${CONV:-patient_ID_conversions.tsv}
 
 ## Requires absolute path 
-LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
@@ -35,7 +32,6 @@ echo "- CONV=${CONV:?}"
 assert_patient_name "${PATIENT}"
 
 assert_file_exists "${CONV}"
-CONV=$(readlink -e "$CONV")
 
 SH_MUTECT2_SUBMIT=${LG3_HOME}/scripts/mutect2_submit.sh
 assert_file_executable "${SH_MUTECT2_SUBMIT}"
@@ -43,13 +39,13 @@ assert_file_executable "${SH_MUTECT2_SUBMIT}"
 echo -n "Submitting jobs for $PATIENT "
 date
 
-## Assert that input files exist
-#D=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
-#assert_directory_exists "${D}"
+## Assert that input directory exists
+D=${LG3_OUTPUT_ROOT}/${PROJECT}/exomes_recal/${PATIENT}
+assert_directory_exists "${D}"
 
 ## Pass QSUB_OPTS to ${SH_MUTECT2_SUBMIT} where it's an optional input
 export QSUB_OPTS
 
-"${SH_MUTECT2_SUBMIT}" "${PATIENT}" "${CONV}" "${PROJECT}" || error "${SH_MUTECT2_SUBMIT} failed"
+"${SH_MUTECT2_SUBMIT}" "${PATIENT}" || error "${SH_MUTECT2_SUBMIT} failed"
 
 echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
diff --git a/runs_demo/_run_PostMut b/runs_demo/_run_PostMut
--- a/runs_demo/_run_PostMut
+++ b/runs_demo/_run_PostMut
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # shellcheck source=scripts/utils.sh
-source "${LG3_HOME}/scripts/utils.sh"
+source "${LG3_HOME:?}/scripts/utils.sh"
+source_lg3_conf
 
 assert_pwd
 
@@ -11,16 +12,12 @@ echo "Call: ${BASH_SOURCE[*]}"
 echo "Script: $PROGRAM"
 echo "Arguments: $*"
 
-LG3_HOME=${LG3_HOME:?}
 LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-output}
 LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-${LG3_OUTPUT_ROOT}}
-PROJECT=${PROJECT:-LG3}
-CONV=${CONV:-patient_ID_conversions.tsv}
 PATIENT=${PATIENT:-Patient157t10}
 EMAIL=${EMAIL:?}
 
 ## Requires absolute path 
-LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
@@ -48,19 +45,20 @@ echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"
 
 assert_file_exists "${CONV}"
 
-PBS=${LG3_HOME}/post_mutect_pindel.pbs
-assert_file_exists "${PBS}"
-
 SH_CHK_PINDEL=${LG3_HOME}/scripts/chk_pindel.sh
 assert_file_executable "${SH_CHK_PINDEL}"
 
 SH_CHK_MUTDET=${LG3_HOME}/scripts/chk_mutdet.sh
 assert_file_executable "${SH_CHK_MUTDET}"
 
-"${SH_CHK_PINDEL}" "${PROJECT}" "${PATIENT}" || error "${SH_CHK_PINDEL} failed"
-"${SH_CHK_MUTDET}" "${PROJECT}" "${PATIENT}" || error "${SH_CHK_MUTDET} failed"
+PBS=${LG3_HOME}/post_mutect_pindel.pbs
+assert_file_exists "${PBS}"
+
+
+"${SH_CHK_PINDEL}" "${PATIENT}" || error "${SH_CHK_PINDEL} failed"
+"${SH_CHK_MUTDET}" "${PATIENT}" || error "${SH_CHK_MUTDET} failed"
 
 # shellcheck disable=SC2086
-qsub ${QSUB_OPTS} -N ${PATIENT}_comb -v "${QSUB_ENVVARS},PATIENT=${PATIENT},PROJECT=${PROJECT},CONV=${CONV}" "$PBS"
+qsub ${QSUB_OPTS} -N ${PATIENT}_comb -v "${QSUB_ENVVARS},PATIENT=${PATIENT}" "$PBS"
 
 echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
