ROBUSTNESS: Run scripts now assert that scripts and input files/folders exist

diff --git a/runs_demo/_run_Align_gz_P157 b/runs_demo/_run_Align_gz_P157
--- a/runs_demo/_run_Align_gz_P157
+++ b/runs_demo/_run_Align_gz_P157
@@ -33,6 +33,9 @@ echo "Qsub extras:"
 echo "- QSUB_OPTS=${QSUB_OPTS}"
 echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"
 
+PBS=${LG3_HOME}/Align_fastq.pbs
+[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
+
 ## Location of output: aligned BAMs
 ALIGN=${LG3_OUTPUT_DIR}/exomes
 
@@ -55,7 +58,7 @@ do
 		else
 		        echo "Submitting $PREFIX ..."
 		        # shellcheck disable=SC2086
-			qsub ${QSUB_OPTS} -N Align_$PREFIX -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},PREFIX=${PREFIX}" "${LG3_HOME}/Align_fastq.pbs"
+			qsub ${QSUB_OPTS} -N Align_$PREFIX -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},PREFIX=${PREFIX}" "${PBS}"
 		fi
 	fi
 done
diff --git a/runs_demo/_run_MutDet_P157 b/runs_demo/_run_MutDet_P157
--- a/runs_demo/_run_MutDet_P157
+++ b/runs_demo/_run_MutDet_P157
@@ -15,20 +15,24 @@ LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
-echo "- LG3_HOME=${LG3_HOME}"
-echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
+echo "- LG3_HOME=${LG3_HOME:?}"
+echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
 echo "- EMAIL=${EMAIL}"
 
 PATIENT=Patient157
 PROJ=LG3
 
 CONV=patient_ID_conversions.txt
+[[ -f "$CONV" ]] || { echo "File not found: ${CONV}"; exit 1; }
 
 ## Requires absolute path 
 #TODO# CONV=$(readlink -e "$CONV")
 
+SCRIPT=${LG3_HOME}/scripts/mutdet_submit.sh
+[[ -x "$SCRIPT" ]] || { echo "File not found or not an executable: ${SCRIPT}"; exit 1; }
+
 echo -n "Submitting jobs for $PATIENT "
 date
-"${LG3_HOME}/scripts/mutdet_submit.sh" $PATIENT $CONV $PROJ
+"${SCRIPT}" $PATIENT $CONV $PROJ
 
 echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
diff --git a/runs_demo/_run_Pindel_157 b/runs_demo/_run_Pindel_157
--- a/runs_demo/_run_Pindel_157
+++ b/runs_demo/_run_Pindel_157
@@ -17,8 +17,8 @@ LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
-echo "- LG3_HOME=${LG3_HOME}"
-echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
+echo "- LG3_HOME=${LG3_HOME:?}"
+echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
 echo "- EMAIL=${EMAIL}"
 
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
@@ -37,11 +37,13 @@ PATIENT=Patient157
 PROJ=LG3
 
 CONV=patient_ID_conversions.txt
+[[ -f "$CONV" ]] || { echo "File not found: ${CONV}"; exit 1; }
 
 ## Requires absolute path 
 #TODO# CONV=$(readlink -e "$CONV")
 
 PBS=${LG3_HOME}/pindel_all.pbs
+[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
 
 
 # shellcheck disable=SC2086
diff --git a/runs_demo/_run_PostMut_P157 b/runs_demo/_run_PostMut_P157
--- a/runs_demo/_run_PostMut_P157
+++ b/runs_demo/_run_PostMut_P157
@@ -15,8 +15,8 @@ LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
-echo "- LG3_HOME=${LG3_HOME}"
-echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
+echo "- LG3_HOME=${LG3_HOME:?}"
+echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
 echo "- EMAIL=${EMAIL}"
 
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
@@ -35,14 +35,22 @@ PATIENT=Patient157
 PROJ=LG3
 
 CONV=patient_ID_conversions.txt
+[[ -f "$CONV" ]] || { echo "File not found: ${CONV}"; exit 1; }
 
 ## Requires absolute path 
 #TODO# CONV=$(readlink -e "$CONV")
 
 PBS=${LG3_HOME}/post_mutect_pindel.pbs
+[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
 
-"${LG3_HOME}/scripts/chk_pindel.sh" $PATIENT
-"${LG3_HOME}/scripts/chk_mutdet.sh" $PATIENT
+SCRIPT_A=${LG3_HOME}/scripts/chk_pindel.sh
+[[ -x "$SCRIPT_A" ]] || { echo "File not found or not an executable: ${SCRIPT_A}"; exit 1; }
+
+SCRIPT_B=${LG3_HOME}/scripts/chk_mutdet.sh
+[[ -x "$SCRIPT_B" ]] || { echo "File not found or not an executable: ${SCRIPT_B}"; exit 1; }
+
+"${SCRIPT_A}" $PATIENT
+"${SCRIPT_B}" $PATIENT
 
 # shellcheck disable=SC2086
 qsub ${QSUB_OPTS} -N ${PATIENT}_comb -v "${QSUB_ENVVARS},PATIENT=${PATIENT},PROJ=${PROJ},CONV=${CONV}" "$PBS"
diff --git a/runs_demo/_run_Recal_P157_3 b/runs_demo/_run_Recal_P157_3
--- a/runs_demo/_run_Recal_P157_3
+++ b/runs_demo/_run_Recal_P157_3
@@ -15,8 +15,8 @@ LG3_HOME=$(readlink -e "$LG3_HOME")
 LG3_OUTPUT_ROOT=$(readlink -e "$LG3_OUTPUT_ROOT")
 
 echo "Input:"
-echo "- LG3_HOME=${LG3_HOME}"
-echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT}"
+echo "- LG3_HOME=${LG3_HOME:?}"
+echo "- LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:?}"
 echo "- EMAIL=${EMAIL}"
 
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
@@ -32,10 +32,13 @@ echo "- QSUB_OPTS=${QSUB_OPTS}"
 echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"
 
 ILIST=resources/SeqCap_EZ_Exome_v3_capture.interval_list
+[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
 
 PBS=${LG3_HOME}/Recal_bigmem.pbs
+[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
 
 D=${LG3_OUTPUT_DIR}/exomes
+[[ -d "$D" ]] || { echo "Directory not found: ${D}"; exit 1; }
 
 ## Requires absolute path 
 #TODO# D=$(readlink -e "$D")
@@ -48,9 +51,9 @@ SUFF=trim.bwa.sorted.bam
 CNT=0
 for N in $(seq 599 601)
 do
-	((CNT++))
-	B=$D/Z00$N/Z00$N.$SUFF
- 	if [ ! -f "$B" ]; then
+   ((CNT++))
+   B=$D/Z00$N/Z00$N.$SUFF
+   if [ ! -f "$B" ]; then
       echo "ABORT: Can't open $B !"
       exit 1
    fi
diff --git a/runs_demo/_run_Trim_P157 b/runs_demo/_run_Trim_P157
--- a/runs_demo/_run_Trim_P157
+++ b/runs_demo/_run_Trim_P157
@@ -38,6 +38,7 @@ echo "- QSUB_OPTS=${QSUB_OPTS}"
 echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"
 
 PBS=${LG3_HOME}/trim_galore.pbs
+[[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
 
 echo "ETA ~4h"
 
