BUG FIX: The pipeline did not support FASTQ file names with undercores (`_`) and suffixes after `_R1`/_R2` [#78, #79]

diff --git a/runs_demo/_run_Trim b/runs_demo/_run_Trim
--- a/runs_demo/_run_Trim
+++ b/runs_demo/_run_Trim
@@ -50,22 +50,29 @@ echo "ETA ~4h"
 
 QTY=20
 
-for SAMPLE in ${SAMPLES}
-do
-   FASTQ1=${LG3_INPUT_ROOT}/${SAMPLE}_R1.fastq.gz
-   FASTQ2=${LG3_INPUT_ROOT}/${SAMPLE}_R2.fastq.gz
+for SAMPLE in ${SAMPLES}; do
+    ## Use file globbing to allow for optional suffixes after _R1 and _R2.
+    ## FIXME: shopt -s nullglob  ## Return empty array if no matches are found
+    FASTQ1s=("${LG3_INPUT_ROOT}/${SAMPLE}_R1"*.fastq.gz)
+    FASTQ2s=("${LG3_INPUT_ROOT}/${SAMPLE}_R2"*.fastq.gz)
 
-   ## Requires absolute path 
-   FASTQ1=$(readlink -e "$FASTQ1")
-   FASTQ2=$(readlink -e "$FASTQ2")
+    ## Assert that at most single files were found by globbing
+    [[ ${#FASTQ1s[@]} -eq 1 ]] || { echo "ERROR: Expected one file: [${#FASTQ1s[@]}] ${FASTQ1s[*]}"; exit 1; }
+    [[ ${#FASTQ2s[@]} -eq 1 ]] || { echo "ERROR: Expected one file: [${#FASTQ2s[@]}] ${FASTQ2s[*]}"; exit 1; }
+
+    ## Requires absolute path 
+    FASTQ1=$(readlink -e "${FASTQ1s[0]}")
+    FASTQ2=$(readlink -e "${FASTQ2s[0]}")
    
-   if [ ! -r "${FASTQ1}" ] || [ ! -r "${FASTQ2}" ]; then
-      echo "ERROR: Can't open $SAMPLE from ${LG3_INPUT_ROOT}/"
-   else
-      echo "Submitting $SAMPLE: quality $QTY ..."
-      # shellcheck disable=SC2086
-      qsub ${QSUB_OPTS} -N trim${QTY}_$SAMPLE -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},SAMPLE=${SAMPLE},QTY=${QTY},PROJECT=${PROJECT}" "$PBS"
-   fi
+    [[ -r "${FASTQ1}" ]] || { echo "ERROR: Can't open $SAMPLE from ${LG3_INPUT_ROOT}/: ${FASTQ1}"; exit 1; }
+    [[ -r "${FASTQ2}" ]] || { echo "ERROR: Can't open $SAMPLE from ${LG3_INPUT_ROOT}/: ${FASTQ2}"; exit 1; }
+
+    echo "Submitting $SAMPLE: quality $QTY ..."
+    echo "- FASTQ1: ${FASTQ1}"
+    echo "- FASTQ2: ${FASTQ2}"
+    
+    # shellcheck disable=SC2086
+    qsub ${QSUB_OPTS} -N trim${QTY}_$SAMPLE -v "${QSUB_ENVVARS},FASTQ1=${FASTQ1},FASTQ2=${FASTQ2},SAMPLE=${SAMPLE},QTY=${QTY},PROJECT=${PROJECT}" "$PBS"
 done
 
 echo "[$(date +'%Y-%m-%d %H:%M:%S %Z')] END: $PROGRAM"
