tweak

diff --git a/runs_demo/_run_Recal b/runs_demo/_run_Recal
--- a/runs_demo/_run_Recal
+++ b/runs_demo/_run_Recal
@@ -39,16 +39,16 @@ echo "- ILIST=${ILIST:?}"
 [[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
 ILIST=$(readlink -e "$ILIST")
 
+## Assert that (NORMAL, SAMPLE, 'Normal') exists in ILIST
+for SAMPLE in ${SAMPLES}; do
+    grep -q -P "^${NORMAL}\\t[^\\t]+\\t${PATIENT}\\tNormal" "${ILIST}" || { echo "ERROR: No such (NORMAL, SAMPLE) = (${NORMAL}, ${SAMPLE}) entry in ILIST: ${ILIST}"; exit 1; }
+done
+
 ## Assert that NORMAL is one of the SAMPLES
 echo "${SAMPLES}" | grep -q -P "(^|\\t| )${NORMAL}(\\t| |$)" || { echo "ERROR: NORMAL '${NORMAL}' is not part of SAMPLES: ${SAMPLES}"; exit 1; }
 
 ## Assert that (NORMAL, PATIENT, 'Normal') exists in ILIST
 grep -q -P "^${NORMAL}\\t[^\\t]+\\t${PATIENT}\\tNormal" "${ILIST}" || { echo "ERROR: No such (NORMAL, PATIENT, 'Normal') = (${NORMAL}, ${PATIENT}, 'Normal') entry in ILIST: ${ILIST}"; exit 1; }
-
-## Assert that (NORMAL, SAMPLE, 'Normal') exists in ILIST
-for SAMPLE in ${SAMPLES}; do
-    grep -q -P "^${NORMAL}\\t[^\\t]+\\t${PATIENT}\\tNormal" "${ILIST}" || { echo "ERROR: No such (NORMAL, SAMPLE) = (${NORMAL}, ${PATIENT}) entry in ILIST: ${ILIST}"; exit 1; }
-done
 
 
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
