ROBUSTNESS: Now `_run_Recal` and `Recal_bigmem.pbs` asserts that there exists a (NORMAL, PATIENT, 'Normal') entry in the patient file (ILIST) [#55]

diff --git a/runs_demo/_run_Recal b/runs_demo/_run_Recal
--- a/runs_demo/_run_Recal
+++ b/runs_demo/_run_Recal
@@ -35,6 +35,13 @@ echo "- NORMAL=${NORMAL:?}"
 echo "- PATIENT=${PATIENT:?}"
 echo "- ILIST=${ILIST:?}"
 
+## Assert that the patient file exists
+[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
+ILIST=$(readlink -e "$ILIST")
+
+## Assert that (NORMAL, PATIENT, 'Normal') exists in ILIST
+grep -q -P "^${NORMAL}\\t[^\\t]+\\t${PATIENT}\\tNormal" "${ILIST}" || { echo "ERROR: No such (NORMAL, PATIENT, 'Normal') = (${NORMAL}, ${PATIENT}, 'Normal') entry in ILIST: ${ILIST}"; exit 1; }
+
 QSUB_ENVVARS="LG3_HOME=${LG3_HOME},LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT},EMAIL=${EMAIL}"
 QSUB_OPTS="${QSUB_OPTS} -d ${PWD:?}"
 
@@ -46,9 +53,6 @@ fi
 echo "Qsub extras:"
 echo "- QSUB_OPTS=${QSUB_OPTS}"
 echo "- QSUB_ENVVARS=${QSUB_ENVVARS}"
-
-[[ -f "$ILIST" ]] || { echo "File not found: ${ILIST}"; exit 1; }
-ILIST=$(readlink -e "$ILIST")
 
 PBS=${LG3_HOME}/Recal_bigmem.pbs
 [[ -f "$PBS" ]] || { echo "File not found: ${PBS}"; exit 1; }
